# Generated by Django 5.1.1 on 2024-09-05 06:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
