# Generated by Django 5.0.6 on 2024-09-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_alter_page_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Yangi Sahifa', 'verbose_name_plural': 'Yangi Sahifa'},
        ),
    ]
