# Generated by Django 5.0.6 on 2024-09-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_menu_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='menu',
        ),
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
