# Generated by Django 5.0.6 on 2024-09-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_remove_page_menu_page_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='Image/Fayl')),
            ],
            options={
                'verbose_name': 'Fayl',
                'verbose_name_plural': 'Fayl',
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='Image/Partners')),
            ],
            options={
                'verbose_name': 'Hamkorlar',
                'verbose_name_plural': 'Hamkorlar',
                'db_table': 'partners',
            },
        ),
    ]
