# Generated by Django 5.0.6 on 2024-09-05 10:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_file_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
